sudo: required
language: node_js
services:
- docker
env:
- CI=1
before_install:
- sudo service postgresql stop
before_script:
- npx gulp create-version-sha
- docker-compose up -d
- (cd pace-pdf;npm install)
- npx gulp create-pace-db
script:
- "./run_all_tests.sh"
deploy:
  - provider: script
    script: bash .travis/deploy.sh dev
    on:
      branch: master
  - provider: script
    script: bash .travis/deploy.sh prod
    on:
      branch: master
