db:
  image: postgres:alpine
  ports:
    - "5432:5432"
  volumes:
    - pace-db-volume:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=pgtester
    - POSTGRES_PASSWORD=pgtester
    - POSTGRES_DB=pace
redis:
  image: redis
  ports:
    - "6379:6379"
pace-pdf:
  build: pace-pdf
  links:
    - redis
  volumes:
    - data-volume:/data
  environment:
    - REDIS_URL=redis://redis:6379
  ports:
    - "3001:3001"
