db:
  image: postgres:alpine
  ports:
    - "5432:5432"
  volumes:
    - pace-db-volume:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=pgtester
    - POSTGRES_PASSWORD=pgtester
    - POSTGRES_DB=pace
redis:
  image: redis
pace-pdf:
  build: pace-pdf
  links:
    - redis
  volumes:
    - data-volume:/pdf
  environment:
    - REDIS_URL=redis://redis:6379
  ports:
    - "3001:3001"
pace-app:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - data-volume:/pdf
  links:
    - db
    - redis
  environment:
    - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    - ADMIN_TOKEN=${ADMIN_TOKEN}
    - COOKIE_SECRET=${COOKIE_SECRET}
    - DATABASE_URL=postgres://pgtester:pgtester@db/pace
    - REDIS_URL=redis://redis:6379
