apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-app-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pace-app
          env:
          - name: "NODE_ENV"
            value: "production"
          - name: "PACE_URL"
            value: "https://www.lauf-gegen-rechts.de"
          - name: "PACE_PDF_URL"
            value: "http://prod-pace-pdf:3001"
