namePrefix: prod-
commonLabels:
  variant: production
bases:
- ../../base/
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- pdf-deployment.yaml
- nfs-pod.yaml
configMapGenerator:
- name: config
  behavior: merge
  files:
    - local.yml
