apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-pdf-app-deployment
spec:
  replicas: 1
  template:
    spec:
      volumes:
       - name: "data"
         nfs:
           server: 10.245.232.242
           path: "/"
      containers:
      - name: pace-pdf-app
        env:
        - name: "NODE_ENV"
          value: "production"
