apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: pace-app-deployment
    spec:
      initContainers:
      - name: db-migrate
        image: pacerunning/pace-app
        command: ['npx', 'db-migrate', 'up', '-e', 'k8s']
        env:
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
      containers:
      - name: pace-app
        image: pacerunning/pace-app
        ports:
        - containerPort: 3000
        env:
        - name: "NODE_ENV"
          value: "base"
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
        - name: "REDIS_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: REDIS_URL
        - name: "ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: ADMIN_PASSWORD
        - name: "ADMIN_TOKEN"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: ADMIN_TOKEN
        - name: "COOKIE_SECRET"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: COOKIE_SECRET

