apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: pace-app-deployment
    spec:
      initContainers:
      - name: db-migrate
        image: pacerunning/pace-app
        command: ['npx', 'db-migrate', 'up']
        env:
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
      containers:
      - name: pace-app
        image: pacerunning/pace-app
        ports:
        - containerPort: 3000
        env:
        - name: "DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
        - name: "REDIS_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: REDIS_URL
