# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: pace-app

resources:
- deployment.yaml
- service.yaml

secretGenerator:
- name: db-secrets
  type: Opaque
  envs: 
    - secrets.env

configMapGenerator:
- name: config
  files:
    - local.yml
