# Example configuration for the webserver
# at https://github.com/monopole/hello

resources:
- deployment.yaml
- pdf-deployment.yaml
- service.yaml
- storage.yaml
- nfs-pod.yaml

secretGenerator:
- name: db-secrets
  type: Opaque
  envs: 
    - secrets.env

configMapGenerator:
- name: config
  files:
    - local.yml
