apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-pdf-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: pace-pdf-app-deployment
    spec:
      volumes:
       - name: "data"
         nfs:
           server: nfs-server
           path: "/"
           readOnly: false
      containers:
      - name: pace-pdf-app
        image: pacerunning/pace-pdf
        ports:
        - containerPort: 3001
        env:
        - name: "PACE_PDF_PATH"
          value: "/data"
        - name: "NODE_ENV"
          value: "base"
        - name: "REDIS_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: REDIS_URL
        volumeMounts:
          - mountPath: "/data"
            name: "data"

---
apiVersion: v1
kind: Service
metadata:
  name: pace-pdf
spec:
  ports:
    - name: pace-pdf
      port: 3001
  selector:
    deployment: pace-pdf-app-deployment
