apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-pdf-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: pace-pdf-app-deployment
    spec:
      containers:
      - name: pace-pdf-app
        image: pacerunning/pace-pdf
        ports:
        - containerPort: 3001
        env:
        - name: "NODE_ENV"
          value: "base"
        - name: "REDIS_URL"
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: REDIS_URL
