kind: Service
apiVersion: v1
metadata:
  name: pace-app-service
spec:
  selector:
    deployment: pace-app-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
