apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace-app-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: pace-app
        env:
          name: "NODE_ENV"
          value: "dev"
