namePrefix: dev-
commonLabels:
  variant: dev
bases:
- ../../base/
patchesStrategicMerge:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: config
  behavior: merge
  files:
    - local.yml
