apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      volumes:
        - name: nfs-vol
          persistentVolumeClaim:
            claimName: dev-pdf-pvc
